# # ? Run test on preview
name: Playwright Tests
on:
  # pull_request:
  #   branches: [development]
  workflow_run:
    workflows: [Vercel]
    types:
      - completed
    # deployment_status:
jobs:
  on-success:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - run: echo 'The triggering workflow passed'
        timeout-minutes: 60
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install -g pnpm && pnpm install

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run test #Wait for deployment to complete and run Playwright tests
        run: npx wait-on https://preview.waverd.com && npx playwright test
        env:
          NODE_ENV: test

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7
  on-failure:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'failure' }}
    steps:
      - run: echo 'The triggering workflow failed'
#
# # ? Run test locally on github
# name: Playwright Tests
# on:
#   push:
#     branches: [main, development]
#   pull_request:
#     branches: [main, development]
# jobs:
#   test:
#     timeout-minutes: 60
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v4
#         with:
#           node-version: lts/*

#       - name: Install dependencies and concurrently # to allow running dev and test together
#         run: npm install -g pnpm && pnpm install && pnpm install concurrently --save-dev

#       - name: Install Playwright Browsers
#         run: pnpm exec playwright install --with-deps

#       - name: Start client and run Playwright tests
#         # run: npm run test:playwright
#         run: npm run dev & npx wait-on http://localhost:3000 && npx playwright test
#         env:
#           NODE_ENV: test

#       - uses: actions/upload-artifact@v4
#         if: ${{ !cancelled() }}
#         with:
#           name: playwright-report
#           path: playwright-report/
#           retention-days: 30
