name: "Vercel Production Deployment"

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  workflow_run:
    workflows: ["Playwright Tests"]
    types:
      - completed

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    # if: ${{ github.event.workflow_run.head_branch == 'main' }}
    concurrency:
      group: pr-${{  github.event.workflow_run.pull_requests.number  }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm install -g pnpm
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
